#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend anemdevop
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 58673-web-01 54.90.33.35
    server 58673-web-02  52.87.153.190 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
