#!/usr/bin/env bash
#Display numbers from 1 to 100:
#Display FizzBuzz when the number is a multiple of 3 and 5
#Display Fizz when the number is multiple of 3
#Display Buzz when the number is multiple of 5
#Otherwise display the number
#In a list format

for n in {1..100}
do
if (( n % 3 == 0 && n % 5 == 0 ))
then
echo "FizzBuzz"
elif (( n % 3 == 0 ))
then
echo "Fizz"
elif (( n % 5 == 0 ))
then
echo "Buzz"
else
echo "$n"
fi
done
