#!/usr/bin/env bash
#Display the content of the file /etc/passwd
#Should only display:
#username
#user id
#Home dirctory path for the user

while read -r passwd; do
echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
