#!/usr/bin/env bash
# Display 'bad luck for 4th iteration
# good luck for 8th iteration
# Best School for other iterations

i=1
while [ $i -lt 11 ]
do
if [ $i -eq 4 ]
then
echo "bad luck"
elif [ $i -eq 8 ]
then
echo "good luck"
else
echo "Best School"
fi
(( i++ ))
done
