#!/usr/bin/env bash
#Display numbers from 1 to 20 and:
#Display 4 and then bad luck from China for 4th iteration
#Display 9 and then bad luck from Japan for 9th iteration
#Display 17 and then bad luck from Italy for 17th iteration

i=1
while [ $i -lt 21 ]
do
echo "$i"
case $i in
"4") echo "bad luck from China";;
"9") echo "bad luck from Japan";;
"17") echo "bad luck from Italy";;
esac
(( i++ ))
done
