#!/usr/bin/env bash
#Display the content of the current directory
#in a list format where only the part of the name
#after the first dash is diplayed

list=$(ls)
for i in $list; do
echo "$i" | cut -d '-' -f2
done
