#!/usr/bin/ env bash
# Changes the followinng domain resolve IPs
#   Localhost from 127.0.0.1 to 127.0.0.2
#   Facebook.com from 157.240.11.35 to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
