#!/usr/bin/ env bash
# Changes the followinng domain resolve IPs
#   Localhost from 127.0.0.1 to 127.0.0.2
#   Facebook.com from 157.240.11.35 to 8.8.8.8

cp /etc/hosts new_hosts
sed -i s/^127.*/"127.0.0.2 localhost"/ new_hosts
echo "8.8.8.8 facebook.com" >> new_hosts
cp new_hosts /etc/hosts
